learning_rate: 0.00005 
batch_size: 8
num_epochs: 10
max_seq_length: 128
image_size: 384
train_val_split: 0.8
output_dir: ./output
save_steps: 500
evaluation_steps: 100
seed: 42
tokenizer_name: "aubmindlab/bert-base-arabertv02"
model_name: "microsoft/trocr-base-printed"